version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: livraria_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: livraria
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    build: .
    container_name: livraria_app
    depends_on:
      - db
    environment:
      - FLASK_APP=main.py  
    ports:
      - "5001:5000"
    volumes:
      - ./app:/app
    command: flask run --host=0.0.0.0

volumes:
  db_data:
